services:
  nginx:
    image: nginx:1.22.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/skeycloak.loseyourip.com.pem:/etc/ssl/certs/skeycloak.loseyourip.com.pem:ro
      - /etc/ssl/private/skeycloak.loseyourip.com.key:/etc/ssl/private/skeycloak.loseyourip.com.key:ro
