---
# Bastion playbook - Docker container approach
- name: Deploy Bastion Hosts
  hosts: bastion
  become: yes
  vars:
    domain_name: "keycloak.ipb.pt"
    keepalived_vip_cidr: 27
    vip: "193.136.194.100"
    interface: "enX0"

  tasks:
    - name: Stop and disable system nginx service
      systemd:
        name: nginx
        state: stopped
        enabled: no
        daemon_reload: yes
      ignore_errors: yes

    - name: Remove system nginx package completely
      apt:
        name: nginx
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Install required packages
      apt:
        name:
          - keepalived
          - curl
          - docker.io
          - docker-compose
          - psmisc
        state: present
        update_cache: yes

    - name: Deploy nginx health check script for keepalived
      template:
        src: ../templates/check_nginx.sh.j2
        dest: /etc/keepalived/check_nginx.sh
        owner: root
        group: root
        mode: "0755"

    - name: Ensure check_nginx.sh is executable
      file:
        path: /etc/keepalived/check_nginx.sh
        mode: "0755"
        owner: root
        group: root
        state: file

    - name: Ensure check_nginx.sh is owned by root
      ansible.builtin.command:
        cmd: chown root:root /etc/keepalived/check_nginx.sh
      become: yes
      changed_when: false

    - name: Template keepalived config for public VIP
      template:
        src: "../templates/keepalived.conf.j2"
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: "0644"
      vars:
        vrrp_instance_name: "PUBLICVIP"
        keepalived_vrid: 50
        keepalived_vip: "{{ vip }}" # Set your public VIP here

    - name: Restart keepalived for public VIP
      systemd:
        name: keepalived
        state: restarted
        enabled: yes

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      loop:
        - /opt/iam-bastion
        - /etc/ssl/private

    - name: Copy Keycloak SSL certificates
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      loop:
        - src: "{{ playbook_dir }}/../../secrets/.lego/certificates/keycloak.ipb.pt.pem"
          dest: /etc/ssl/certs/keycloak.ipb.pt.pem
          mode: "0644"
        - src: "{{ playbook_dir }}/../../secrets/.lego/certificates/keycloak.ipb.pt.key"
          dest: /etc/ssl/private/keycloak.ipb.pt.key
          mode: "0600"
      ignore_errors: yes

    - name: Copy Grafana SSL certificates (both) to all bastions
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      loop:
        - src: "{{ playbook_dir }}/../../secrets/.lego/certificates/grafana1.ccom.ipb.pt.pem"
          dest: /etc/ssl/certs/grafana1.ccom.ipb.pt.pem
          mode: "0644"
        - src: "{{ playbook_dir }}/../../secrets/.lego/certificates/grafana1.ccom.ipb.pt.key"
          dest: /etc/ssl/private/grafana1.ccom.ipb.pt.key
          mode: "0600"
        - src: "{{ playbook_dir }}/../../secrets/.lego/certificates/grafana2.ccom.ipb.pt.pem"
          dest: /etc/ssl/certs/grafana2.ccom.ipb.pt.pem
          mode: "0644"
        - src: "{{ playbook_dir }}/../../secrets/.lego/certificates/grafana2.ccom.ipb.pt.key"
          dest: /etc/ssl/private/grafana2.ccom.ipb.pt.key
          mode: "0600"
      ignore_errors: yes

    - name: Copy Docker Compose configuration from repository
      copy:
        src: "{{ playbook_dir }}/../../docker/bastion/docker-compose.yml"
        dest: /opt/iam-bastion/docker-compose.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"
        remote_src: no

    - name: Copy nginx configuration from repository
      copy:
        src: "{{ playbook_dir }}/../../docker/bastion/nginx.conf"
        dest: /opt/iam-bastion/nginx.conf
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"
        remote_src: no

    - name: Start Docker nginx service
      shell: |
        cd /opt/iam-bastion
        docker compose down || true
        docker compose up -d
      register: docker_result

    - name: Show Docker compose output
      debug:
        var: docker_result

    - name: Wait for nginx container to be ready
      wait_for:
        port: 80
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 60

    - name: Wait for nginx HTTPS to be ready
      wait_for:
        port: 443
        host: "{{ ansible_default_ipv4.address }}"
        delay: 10
        timeout: 60

    - name: Test nginx container health
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:80/"
        method: GET
        timeout: 10
      register: nginx_health
      ignore_errors: yes

    - name: Display nginx health result
      debug:
        msg: "Nginx container: {{ 'HEALTHY' if nginx_health.status == 200 or nginx_health.status == 301 or nginx_health.status == 302 else 'UNHEALTHY' }}"

    - name: Display service endpoints
      debug:
        msg: |
          Bastion services deployed on {{ ansible_hostname }} ({{ ansible_default_ipv4.address }}):
          - HTTP: http://{{ ansible_default_ipv4.address }}:80
          - HTTPS: https://{{ ansible_default_ipv4.address }}:443
          - Public Domain: https://{{ domain_name }}
